<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class AchievementsSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        DB::table('achievements')->insert([

            // ---------------------------------------------------
            // 🟦 COMMON (iniciais – básicos)
            // ---------------------------------------------------
            [
                'title' => 'Primeiro Login',
                'description' => 'Acesse o aplicativo pela primeira vez.',
                'xp_reward' => 10,
                'rarity' => 'common',
                'icon' => 'first_login',
                'status' => 'locked',
                'auto_claim' => true, // XP automático
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'Primeira Meta Criada',
                'description' => 'Crie sua primeira meta financeira.',
                'xp_reward' => 20,
                'rarity' => 'common',
                'icon' => 'first_goal',
                'status' => 'locked',
                'auto_claim' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'Primeira Receita',
                'description' => 'Registre sua primeira receita.',
                'xp_reward' => 10,
                'rarity' => 'common',
                'icon' => 'first_income',
                'status' => 'locked',
                'auto_claim' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'Primeira Despesa',
                'description' => 'Registre sua primeira despesa.',
                'xp_reward' => 10,
                'rarity' => 'common',
                'icon' => 'first_expense',
                'status' => 'locked',
                'auto_claim' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'Primeiro Mês Planejado',
                'description' => 'Tenha pelo menos 10 transações registradas no mês.',
                'xp_reward' => 20,
                'rarity' => 'common',
                'icon' => 'first_month',
                'status' => 'locked',
                'auto_claim' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'Primeira Categoria Criada',
                'description' => 'Crie uma categoria personalizada.',
                'xp_reward' => 15,
                'rarity' => 'common',
                'icon' => 'category_custom',
                'status' => 'locked',
                'auto_claim' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'Relatório Visualizado',
                'description' => 'Consulte seu primeiro gráfico mensal.',
                'xp_reward' => 10,
                'rarity' => 'common',
                'icon' => 'chart_view',
                'status' => 'locked',
                'auto_claim' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'Primeiro Orçamento',
                'description' => 'Crie seu primeiro orçamento.',
                'xp_reward' => 20,
                'rarity' => 'common',
                'icon' => 'budget_add',
                'status' => 'locked',
                'auto_claim' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // ---------------------------------------------------
            // 🟩 CONSISTÊNCIA (médio)
            // ---------------------------------------------------
            [
                'title' => '7 Dias Registrando Gastos',
                'description' => 'Registre despesas por 7 dias seguidos.',
                'xp_reward' => 40,
                'rarity' => 'common',
                'icon' => 'streak_7_spending',
                'status' => 'locked',
                'auto_claim' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => '14 Dias Registrando Gastos',
                'description' => 'Registre despesas por 14 dias seguidos.',
                'xp_reward' => 60,
                'rarity' => 'common',
                'icon' => 'streak_14_spending',
                'status' => 'locked',
                'auto_claim' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => '30 Dias Registrando Gastos',
                'description' => 'Registre despesas diariamente por 30 dias.',
                'xp_reward' => 90,
                'rarity' => 'rare',
                'icon' => 'streak_30_spending',
                'status' => 'locked',
                'auto_claim' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => '5 Meses Completos',
                'description' => 'Feche 5 meses consecutivos com registros completos.',
                'xp_reward' => 80,
                'rarity' => 'rare',
                'icon' => 'month_5_complete',
                'status' => 'locked',
                'auto_claim' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'Orçamento Cumprido',
                'description' => 'Feche o mês dentro do orçamento.',
                'xp_reward' => 70,
                'rarity' => 'rare',
                'icon' => 'budget_success',
                'status' => 'locked',
                'auto_claim' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // ---------------------------------------------------
            // 🟧 METAS
            // ---------------------------------------------------
            [
                'title' => 'Meta Concluída',
                'description' => 'Conclua sua primeira meta.',
                'xp_reward' => 50,
                'rarity' => 'common',
                'icon' => 'goal_done',
                'status' => 'locked',
                'auto_claim' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'Economize R$ 100',
                'description' => 'Primeiro marco de economia.',
                'xp_reward' => 50,
                'rarity' => 'common',
                'icon' => 'save_100',
                'status' => 'locked',
                'auto_claim' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'Economize R$ 500',
                'description' => 'Economize meio milheiro.',
                'xp_reward' => 70,
                'rarity' => 'common',
                'icon' => 'save_500',
                'status' => 'locked',
                'auto_claim' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'Economize R$ 1.000',
                'description' => 'Economize seu primeiro mil.',
                'xp_reward' => 90,
                'rarity' => 'rare',
                'icon' => 'save_1000',
                'status' => 'locked',
                'auto_claim' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'Economize R$ 3.000',
                'description' => 'Meta de economia intermediária.',
                'xp_reward' => 110,
                'rarity' => 'rare',
                'icon' => 'save_3000',
                'status' => 'locked',
                'auto_claim' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'Economize R$ 5.000',
                'description' => 'Meta para disciplina financeira.',
                'xp_reward' => 120,
                'rarity' => 'epic',
                'icon' => 'save_5000',
                'status' => 'locked',
                'auto_claim' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => '3 Metas Concluídas',
                'description' => 'Conclua 3 metas pessoais.',
                'xp_reward' => 100,
                'rarity' => 'rare',
                'icon' => 'goals_3',
                'status' => 'locked',
                'auto_claim' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => '5 Metas Concluídas',
                'description' => 'Conclua 5 metas pessoais.',
                'xp_reward' => 120,
                'rarity' => 'epic',
                'icon' => 'goals_5',
                'status' => 'locked',
                'auto_claim' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // ---------------------------------------------------
            // 🟨 RECEITAS E RENDA
            // ---------------------------------------------------
            [
                'title' => 'Renda Extra',
                'description' => 'Adicione uma receita extra.',
                'xp_reward' => 50,
                'rarity' => 'common',
                'icon' => 'income_extra',
                'status' => 'locked',
                'auto_claim' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'Venda Inteligente',
                'description' => 'Registre uma receita de venda.',
                'xp_reward' => 50,
                'rarity' => 'common',
                'icon' => 'sell_item',
                'status' => 'locked',
                'auto_claim' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'Freelancer',
                'description' => 'Registre 10 receitas extras.',
                'xp_reward' => 80,
                'rarity' => 'rare',
                'icon' => 'freelancer',
                'status' => 'locked',
                'auto_claim' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'Renda Estável',
                'description' => 'Registre receitas por 6 meses seguidos.',
                'xp_reward' => 120,
                'rarity' => 'epic',
                'icon' => 'income_stable',
                'status' => 'locked',
                'auto_claim' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // ---------------------------------------------------
            // 🔵 INVESTIMENTOS (power users)
            // ---------------------------------------------------
            [
                'title' => 'Primeiro Investimento',
                'description' => 'Registre seu primeiro investimento.',
                'xp_reward' => 80,
                'rarity' => 'rare',
                'icon' => 'invest_first',
                'status' => 'locked',
                'auto_claim' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'Carteira Montada',
                'description' => 'Registre 5 investimentos diferentes.',
                'xp_reward' => 120,
                'rarity' => 'epic',
                'icon' => 'invest_5',
                'status' => 'locked',
                'auto_claim' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'Dividendos Recebidos',
                'description' => 'Registre uma receita de dividendos.',
                'xp_reward' => 150,
                'rarity' => 'epic',
                'icon' => 'dividends',
                'status' => 'locked',
                'auto_claim' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'R$ 10.000 Investidos',
                'description' => 'Tenha um patrimônio investido de R$ 10.000.',
                'xp_reward' => 250,
                'rarity' => 'epic',
                'icon' => 'invest_10k',
                'status' => 'locked',
                'auto_claim' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'R$ 100.000 Investidos',
                'description' => 'Alcance 100 mil de investimentos.',
                'xp_reward' => 350,
                'rarity' => 'legendary',
                'icon' => 'invest_100k',
                'status' => 'locked',
                'auto_claim' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // ---------------------------------------------------
            // 🟪 DESPESAS E CONTROLE
            // ---------------------------------------------------
            [
                'title' => 'Corte de Gastos',
                'description' => 'Reduza gastos em 10% em relação ao mês anterior.',
                'xp_reward' => 40,
                'rarity' => 'common',
                'icon' => 'cut_expense',
                'status' => 'locked',
                'auto_claim' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'Dívida Eliminada',
                'description' => 'Quite uma dívida completamente.',
                'xp_reward' => 100,
                'rarity' => 'rare',
                'icon' => 'debt_paid',
                'status' => 'locked',
                'auto_claim' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // ---------------------------------------------------
            // 🔥 SECRETAS / LENDÁRIAS
            // ---------------------------------------------------
            [
                'title' => 'Modo Ultra Econômico',
                'description' => 'Economize mais de 50% da renda no mês.',
                'xp_reward' => 400,
                'rarity' => 'legendary',
                'icon' => 'ultra_save',
                'status' => 'locked',
                'auto_claim' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'Magnata Moderno',
                'description' => 'Alcance 1 milhão em patrimônio.',
                'xp_reward' => 900,
                'rarity' => 'legendary',
                'icon' => 'million',
                'status' => 'locked',
                'auto_claim' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'Lenda Financeira',
                'description' => 'Alcance 3 milhões em patrimônio.',
                'xp_reward' => 1000,
                'rarity' => 'legendary',
                'icon' => 'legend_finance',
                'status' => 'locked',
                'auto_claim' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // ---------------------------------------------------
            // 🟫 EDUCAÇÃO / EMPRESAS / ESCOLAS (futuro)
            // ---------------------------------------------------
            [
                'title' => 'Aluno Exemplo',
                'description' => 'Conclua um módulo de educação financeira.',
                'xp_reward' => 60,
                'rarity' => 'common',
                'icon' => 'school_basic',
                'status' => 'locked',
                'auto_claim' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'Curso Completo',
                'description' => 'Conclua todos os módulos de educação financeira.',
                'xp_reward' => 200,
                'rarity' => 'epic',
                'icon' => 'school_master',
                'status' => 'locked',
                'auto_claim' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'Meta da Empresa',
                'description' => 'Complete uma meta corporativa.',
                'xp_reward' => 120,
                'rarity' => 'rare',
                'icon' => 'company_goal',
                'status' => 'locked',
                'auto_claim' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}
